# Generated by Django 3.2 on 2021-12-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakkyokuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('name', models.CharField(max_length=255, verbose_name='ユーザー名')),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='created_date',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='is_on_release',
            new_name='isOnRelease',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='last_updated_date',
            new_name='lastUpdatedDate',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='released_date',
            new_name='releasedDate',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_id',
            new_name='songID',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='user_id',
            new_name='userID',
        ),
    ]
